### ISSUE TITLE
NetShears dependancy with pod : Type 'Bundle' has no member 'module'

### ISSUE THREAD

**Issue by tonicfx** [divar-ir/NetShears#19]
Hello, I try to integrate your library into existing project, with pod dependancy. 

`  pod 'NetShears', :git => 'https://github.com/divar-ir/NetShears.git', :tag => '2.0.3'`

When i compile my project with your pod, I have an erreur during build : 

`XXX/Pods/NetShears/Sources/NetShears/UI/RequestDetailViewController.swift:45:79: error: type 'Bundle' has no member 'module'
        tableView.register(UINib(nibName: "TextTableViewCell", bundle: Bundle.module), forCellReuseIdentifier: "TextTableViewCell")
                                                                       ~~~~~~ ^~~~~~
XXX/Pods/NetShears/Sources/NetShears/UI/RequestDetailViewController.swift:46:85: error: type 'Bundle' has no member 'module'
        tableView.register(UINib(nibName: "ActionableTableViewCell", bundle: Bundle.module), forCellReuseIdentifier: "ActionableTableViewCell")
                                                                             ~~~~~~ ^~~~~~
XXX/Pods/NetShears/Sources/NetShears/UI/RequestDetailViewController.swift:47:85: error: type 'Bundle' has no member 'module'
        tableView.register(UINib(nibName: "RequestTitleSectionView", bundle: Bundle.module), forHeaderFooterViewReuseIdentifier: "RequestTitleSectionView")
                                                                             ~~~~~~ ^~~~~~


Showing Recent Errors Only
/Pods/NetShears/Sources/NetShears/UI/RequestDetailViewController.swift:45:79: Type 'Bundle' has no member 'module'`

It seems your library it only compatible with Swift Package Manager, not with Cocoapods ?

I work with Xcode 13.4.1.

Thanks for your help.

**Comment by pandya293** [comment]
Facing same issue with Netshears 3.2.0 package version.
did you get any solution ?

**Comment by mehdiimrz** [comment]
Thanks @tonicfx for your information.

It should be fixed now

https://github.com/divar-ir/NetShears/pull/20

Let me know if your problem is fixed so we can close this issue
